language: ruby
deploy:
  provider: heroku
  api_key:
    secure: rwS0w1qB3fdy+N9iPuYhQjt6h9bm8NQ1S1DZtTd3TDGNJkD2CiCszU6yZw+Yx08SN8nsLRs7DQJujLiJ/trWMBIwQLS72QlMJex0LHgjL1zZpZc4t+tHAKfIChEmsTV12i9WMBPA47snh2ykngJhXN+F1oLVqzRuVEawazd7IwDHAQ7N7mrS5dQyC0huKVeCJSiLkS4DRzXLTUxUY2QyT2rgDnFq+sbxZ6sxXkoOcyC5ieEnA6nJFscJcrGwpyJCHR3CuX+tBtX0lQ6N02sNnMgIeUsyNNLv4dxV5dc3cCdgMgnqWKQEtTEu3nex01nBUZeAufn+cDVQ3DH65w47fTYROV4/y5tbftINJuG2krtF1RsPjTFDamF4iC3SqshZfDIJ++UKbd1L3iXrE8itXixaS77T4s7YzBO9ZW7SBwP/jUF1WAPitK2uVJA9PYf6Cakd4+jf8W96Ahh+mWlJEQcOD3OPqwBgp8VEdDk/Gme7r29eUCerAya+4nKFvXnYPeaL12s6G4QshifXFqX9Ox2IcFbOoorJj5Qf7mc4jgi5W38Kfw2XbOXoBEW5TeC8uH644Ki4R3e5V6xgKS9ZujkUyWazaSHS1XTz6FnuY+iTU9NkO49L0MfJg5czb6qPUZ3WX0b2YaaKjtNN/hsepEZWHNXEdwchI7Q7QxLdHoM=
  app: my-web-space
